"""reate users table

Revision ID: 011ece88e810
Revises: 1dcf37cce1bf
Create Date: 2024-12-02 19:46:05.898423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011ece88e810'
down_revision = '1dcf37cce1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
